import type { GTMNode, GTMEdge } from "@/types";

export const GTM_NODES: GTMNode[] = [
  // Layer 0 — Data Ingestion (blue)
  {
    id: "signal-crawler",
    label: "Signal Crawler",
    layer: 0,
    x: 120,
    y: 80,
    purpose: "Continuously scrapes web sources, news APIs, and job boards for buying signals.",
    inputs: ["Web sources", "News APIs", "LinkedIn", "Job boards"],
    outputs: ["Raw signal events", "Company activity feed"],
    tools: ["Apify", "PhantomBuster", "Exa", "Tavily"],
    platformRole: "The AI layer enriches raw signals with industry context, flagging relevant strategic initiatives and transformation milestones that generic crawlers miss.",
    color: "#3B82F6",
  },
  {
    id: "crm-sync",
    label: "CRM Sync",
    layer: 0,
    x: 360,
    y: 80,
    purpose: "Maintains bidirectional sync between all GTM tools and the CRM as the system of record.",
    inputs: ["Salesforce / HubSpot", "Engagement data", "Deal history"],
    outputs: ["Unified account records", "Activity history"],
    tools: ["Salesforce", "HubSpot", "Zapier", "Census"],
    platformRole: "AI-generated insights are written back to CRM records automatically, making intelligence accessible to every rep without changing their workflow.",
    color: "#3B82F6",
  },
  {
    id: "intent-feed",
    label: "Intent Feed",
    layer: 0,
    x: 600,
    y: 80,
    purpose: "Aggregates third-party intent signals to identify accounts actively researching relevant solutions.",
    inputs: ["G2 intent data", "Bombora surges", "LinkedIn activity"],
    outputs: ["Intent scores", "In-market account list"],
    tools: ["Bombora", "G2 Buyer Intent", "LinkedIn Sales Nav"],
    platformRole: "The AI layer overlays industry-specific intent signals — RFPs, regulatory filings, strategic reports — that generic intent tools consistently miss.",
    color: "#3B82F6",
  },

  // Layer 1 — AI Processing (cyan)
  {
    id: "account-scorer",
    label: "Account Scorer",
    layer: 1,
    x: 120,
    y: 220,
    purpose: "Scores every account on fit and timing using ML models trained on closed-won data.",
    inputs: ["Signal events", "CRM history", "Intent scores", "Firmographic data"],
    outputs: ["Fit score (0-100)", "Timing score (0-100)", "Priority tier"],
    tools: ["Custom ML", "MadKudu", "6sense"],
    platformRole: "The scoring model is trained on your specific closed-won data, weighting the regulatory timelines, budget cycles, and buying patterns that matter for your ICP.",
    color: "#00D4FF",
  },
  {
    id: "persona-intel",
    label: "Persona Intel",
    layer: 1,
    x: 360,
    y: 220,
    purpose: "Builds executive profiles including communication style, priorities, and likely objections.",
    inputs: ["LinkedIn data", "Published articles", "Conference talks", "CRM notes"],
    outputs: ["Exec profile", "Communication style guide", "Key priorities"],
    tools: ["Clay", "Clearbit", "Apollo"],
    platformRole: "AI generates executive profiles tailored to your solution, mapping each persona's relationship to the strategic priorities your product addresses.",
    color: "#00D4FF",
  },
  {
    id: "competitive-ai",
    label: "Competitive AI",
    layer: 1,
    x: 600,
    y: 220,
    purpose: "Automatically generates and updates competitive battle cards from win/loss data and market signals.",
    inputs: ["Win/loss data", "Competitor news", "Gong call transcripts"],
    outputs: ["Live battle cards", "Competitive positioning matrix"],
    tools: ["Klue", "Crayon", "Custom LLM pipeline"],
    platformRole: "AI monitors competitors in real time, flagging new product announcements and partnership shifts that affect your positioning before your reps walk into a call.",
    color: "#00D4FF",
  },

  // Layer 2 — Content Generation (teal)
  {
    id: "outreach-ai",
    label: "Outreach AI",
    layer: 2,
    x: 240,
    y: 360,
    purpose: "Generates hyper-personalized outreach sequences grounded in account intelligence and exec profiles.",
    inputs: ["Exec profiles", "Fit/timing scores", "Recent signals", "Battle cards"],
    outputs: ["Personalized email sequences", "LinkedIn messages", "Call scripts"],
    tools: ["Claude / GPT-4", "Outreach", "Salesloft"],
    platformRole: "AI is the generation layer — producing first touches that reference specific initiatives, filings, or earnings call language rather than generic value propositions.",
    color: "#14B8A6",
  },
  {
    id: "content-ai",
    label: "Content AI",
    layer: 2,
    x: 520,
    y: 360,
    purpose: "Dynamically assembles sales collateral personalized to account, industry, and buyer role.",
    inputs: ["Account data", "Industry vertical", "Buyer persona", "Use case library"],
    outputs: ["Custom one-pagers", "Personalized decks", "ROI models"],
    tools: ["Claude", "Tome", "Beautiful.ai"],
    platformRole: "AI generates industry-specific ROI models and technical collateral tailored to each buyer context — utility vs. industrial vs. enterprise — on demand.",
    color: "#14B8A6",
  },

  // Layer 3 — Orchestration (purple)
  {
    id: "gtm-orchestrator",
    label: "GTM Orchestrator",
    layer: 3,
    x: 240,
    y: 490,
    purpose: "Central brain that routes signals to the right actions: which rep, which sequence, which channel, when.",
    inputs: ["Priority scores", "Account stage", "Rep capacity", "Campaign calendars"],
    outputs: ["Action assignments", "Sequence triggers", "Escalation alerts"],
    tools: ["Custom workflow engine", "n8n", "Zapier"],
    platformRole: "The AI orchestration layer understands your specific procurement cycles, automatically timing outreach around budget seasons and project milestones.",
    color: "#8B5CF6",
  },
  {
    id: "workflow-engine",
    label: "Workflow Engine",
    layer: 3,
    x: 520,
    y: 490,
    purpose: "Executes trigger-based automation: handoff rules, escalation logic, and multi-channel sequencing.",
    inputs: ["Orchestrator actions", "CRM state changes", "Engagement signals"],
    outputs: ["Automated tasks", "Sequence enrollments", "Slack/email alerts"],
    tools: ["Make (Integromat)", "Zapier", "HubSpot Workflows"],
    platformRole: "AI monitors signal feeds and auto-triggers outreach when relevant events drop — regulatory announcements, funding rounds, leadership changes — without rep intervention.",
    color: "#8B5CF6",
  },

  // Layer 4 — Execution (amber)
  {
    id: "sales-engage",
    label: "Sales Engage",
    layer: 4,
    x: 120,
    y: 620,
    purpose: "Executes personalized outreach sequences across email, phone, and LinkedIn at scale.",
    inputs: ["Generated sequences", "Rep assignments", "Contact data"],
    outputs: ["Sent messages", "Meeting bookings", "Engagement data"],
    tools: ["Outreach.io", "Salesloft", "Apollo"],
    platformRole: "AI-generated sequences plug directly into execution tools — reps review and send, the AI handles research and writing at scale.",
    color: "#FF8C42",
  },
  {
    id: "paid-amplify",
    label: "Paid Amplify",
    layer: 4,
    x: 380,
    y: 620,
    purpose: "Syncs target account lists to paid channels for account-based advertising and retargeting.",
    inputs: ["Prioritized account list", "Buyer personas", "Campaign content"],
    outputs: ["LinkedIn ad audiences", "Google display audiences", "Retargeting lists"],
    tools: ["LinkedIn Campaign Manager", "Demandbase", "RollWorks"],
    platformRole: "AI dynamically updates ad audiences based on real-time account scoring, pausing spend on accounts that go cold and accelerating on accounts heating up.",
    color: "#FF8C42",
  },
  {
    id: "partner-channel",
    label: "Partner Channel",
    layer: 4,
    x: 640,
    y: 620,
    purpose: "Activates channel partners with co-sell intelligence and joint account planning materials.",
    inputs: ["Shared account lists", "Partner profiles", "Co-sell opportunities"],
    outputs: ["Partner briefs", "Joint outreach assets", "Co-sell pipeline"],
    tools: ["Impartner", "PartnerStack", "Crossbeam"],
    platformRole: "AI generates partner-specific account briefs that highlight the intersection between partner capabilities and your solution, enabling faster co-sell activation.",
    color: "#FF8C42",
  },

  // Layer 5 — Feedback (orange)
  {
    id: "convo-intel",
    label: "Convo Intel",
    layer: 5,
    x: 240,
    y: 750,
    purpose: "Analyzes sales call recordings to surface winning patterns, objections, and coaching insights.",
    inputs: ["Call recordings", "Meeting transcripts", "Deal outcomes"],
    outputs: ["Talk track recommendations", "Objection library", "Coaching flags"],
    tools: ["Gong", "Chorus", "Otter.ai"],
    platformRole: "AI extracts industry-specific objection patterns and winning narratives from calls, feeding them back into battle cards and outreach templates automatically.",
    color: "#F97316",
  },
  {
    id: "attribution",
    label: "Attribution",
    layer: 5,
    x: 520,
    y: 750,
    purpose: "Measures which GTM motions, channels, and content actually drive pipeline and revenue.",
    inputs: ["Deal data", "Touchpoint history", "Campaign data", "Engagement signals"],
    outputs: ["Attribution reports", "Channel ROI", "Influenced pipeline"],
    tools: ["Rockerbox", "Triple Whale", "Custom analytics"],
    platformRole: "AI attribution shows which generated content and sequences actually moved deals — giving clear signal on where to invest the next dollar of GTM spend.",
    color: "#F97316",
  },

  // Layer 6 — Optimization (green)
  {
    id: "gtm-dashboard",
    label: "GTM Dashboard",
    layer: 6,
    x: 240,
    y: 880,
    purpose: "Unified real-time view of the entire GTM system: pipeline health, campaign performance, and AI metrics.",
    inputs: ["All layer outputs", "CRM data", "Attribution data"],
    outputs: ["Executive dashboards", "Rep scorecards", "Campaign performance"],
    tools: ["Tableau", "Looker", "Custom Next.js dashboard"],
    platformRole: "AI adds anomaly detection across the entire GTM stack — surfacing when pipeline velocity drops before humans notice the trend and recommending corrective actions.",
    color: "#00FF88",
  },
  {
    id: "model-retraining",
    label: "Model Retraining",
    layer: 6,
    x: 520,
    y: 880,
    purpose: "Closes the feedback loop by using real outcomes to continuously improve scoring and generation models.",
    inputs: ["Win/loss outcomes", "Engagement data", "Attribution results"],
    outputs: ["Updated scoring models", "Improved prompts", "Refined ICP definitions"],
    tools: ["Custom ML pipeline", "Weights & Biases", "LangSmith"],
    platformRole: "The proprietary data flywheel: every closed deal and lost opportunity makes the next AI output smarter. The system compounds in accuracy over time.",
    color: "#00FF88",
  },
];

export const GTM_EDGES: GTMEdge[] = [
  // Layer 0 → Layer 1
  { id: "e1", from: "signal-crawler", to: "account-scorer", animated: true },
  { id: "e2", from: "crm-sync", to: "account-scorer", animated: true },
  { id: "e3", from: "intent-feed", to: "account-scorer", animated: true },
  { id: "e4", from: "crm-sync", to: "persona-intel", animated: true },
  { id: "e5", from: "signal-crawler", to: "competitive-ai", animated: true },
  // Layer 1 → Layer 2
  { id: "e6", from: "account-scorer", to: "outreach-ai", animated: true },
  { id: "e7", from: "persona-intel", to: "outreach-ai", animated: true },
  { id: "e8", from: "competitive-ai", to: "outreach-ai", animated: true },
  { id: "e9", from: "account-scorer", to: "content-ai", animated: true },
  { id: "e10", from: "persona-intel", to: "content-ai", animated: true },
  // Layer 2 → Layer 3
  { id: "e11", from: "outreach-ai", to: "gtm-orchestrator", animated: true },
  { id: "e12", from: "content-ai", to: "gtm-orchestrator", animated: true },
  { id: "e13", from: "gtm-orchestrator", to: "workflow-engine", animated: true },
  // Layer 3 → Layer 4
  { id: "e14", from: "gtm-orchestrator", to: "sales-engage", animated: true },
  { id: "e15", from: "workflow-engine", to: "sales-engage", animated: true },
  { id: "e16", from: "gtm-orchestrator", to: "paid-amplify", animated: true },
  { id: "e17", from: "gtm-orchestrator", to: "partner-channel", animated: true },
  // Layer 4 → Layer 5
  { id: "e18", from: "sales-engage", to: "convo-intel", animated: true },
  { id: "e19", from: "sales-engage", to: "attribution", animated: true },
  { id: "e20", from: "paid-amplify", to: "attribution", animated: true },
  // Layer 5 → Layer 6
  { id: "e21", from: "convo-intel", to: "gtm-dashboard", animated: true },
  { id: "e22", from: "attribution", to: "gtm-dashboard", animated: true },
  { id: "e23", from: "convo-intel", to: "model-retraining", animated: true },
  { id: "e24", from: "attribution", to: "model-retraining", animated: true },
  // Layer 6 → Layer 1 (closes the loop)
  { id: "e25", from: "model-retraining", to: "account-scorer", animated: true },
];

export const LAYER_LABELS: Record<number, { name: string; color: string }> = {
  0: { name: "Data Ingestion", color: "#3B82F6" },
  1: { name: "AI Processing", color: "#00D4FF" },
  2: { name: "Content Generation", color: "#14B8A6" },
  3: { name: "Orchestration", color: "#8B5CF6" },
  4: { name: "Execution", color: "#FF8C42" },
  5: { name: "Feedback", color: "#F97316" },
  6: { name: "Optimization", color: "#00FF88" },
};
